FROM python:3.9.4-slim-buster
ENV PYTHONUNBUFFERED 1

ARG SECRET_KEY
ARG TWITTER_API_TOKEN
ARG TWITTER_API_BASE_URL
ARG GITHUB_API_BASE_URL

ENV SECRET_KEY $SECRET_KEY
ENV TWITTER_API_TOKEN $TWITTER_API_TOKEN
ENV TWITTER_API_BASE_URL $TWITTER_API_BASE_URL
ENV GITHUB_API_BASE_URL $GITHUB_API_BASE_URL

RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/

RUN pip install -r requirements.txt

ADD . /code/

EXPOSE 80 80/tcp
