version: "3.7"

services:
  app:
    image: waglds/challange_jobandtalent:latest
    container_name: challange
    command: sh run.sh
    # to be set with ${} from within the CD tool.
    # hard-coding here for the sake of simplicity.
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TWITTER_API_TOKEN=${TWITTER_API_TOKEN}
      - TWITTER_API_BASE_URL=${TWITTER_API_BASE_URL}
      - GITHUB_API_BASE_URL=${GITHUB_API_BASE_URL}
    ports:
      - "80:80"
