# Generated by Django 3.2 on 2021-04-17 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SocialRegistry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'source_developer',
                    models.CharField(
                        db_index=True,
                        help_text='Username of source developer',
                        max_length=80,
                    ),
                ),
                (
                    'target_developer',
                    models.CharField(
                        db_index=True,
                        help_text='Username of target developer',
                        max_length=80,
                    ),
                ),
                (
                    'transaction_id',
                    models.CharField(
                        help_text='Matching transaction number.',
                        max_length=40,
                        unique=True,
                    ),
                ),
                ('connected', models.BooleanField(default=False)),
                (
                    'registered_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CommonOrganizations',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'transaction_id',
                    models.CharField(
                        help_text='Matching transaction number.',
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    'organization',
                    models.CharField(
                        help_text='Name of organization common to both developers',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'social_registry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='social_connected.socialregistry',
                    ),
                ),
            ],
        ),
    ]
